spring.application.name=postgres

# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=wassim

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Port
server.port=8081

# Désactiver Eureka
eureka.client.enabled=false

# JWT
app.jwtSecret=64CarNovaSuperSecretKey123!ChangeThisForProduction123456
app.jwtExpirationMs=86400000

logging.level.org.springframework.security=DEBUG
logging.level.CarNova.carnova=DEBUG

spring.web.resources.static-locations=classpath:/static/,file:./uploads/

# ============ Assistant IA (100% local, gratuit) ============
# Forcer Ollama comme provider
ai.provider=ollama

# OpenAI désactivé (pas de facturation)
openai.api.key=
ai.openai.model=gpt-4o-mini

# Ollama (assure-toi que 'ollama serve' tourne)
ai.ollama.url=http://localhost:11434
# Modèle très rapide que tu as déjà: gemma3:1b
ai.ollama.model=gemma3:1b

# (optionnel) Fallback vers Ollama si un jour tu remets OpenAI en principal
ai.fallbackToOllama=true
# ============================================================

# Stripe
stripe.secret.key=${STRIPE_SECRET_KEY}




# Limites multipart (à ajuster)
spring.servlet.multipart.max-file-size=15MB
spring.servlet.multipart.max-request-size=20MB

# (optionnel) un peu plus de temps pour l?upload
server.tomcat.connection-timeout=30s





# (ajouter à la fin)
spring.jackson.time-zone=Africa/Tunis
carnova.cors.allowed-origins=http://localhost:4200
# déjà présent pour SQL, on ajoute les binds
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=TRACE
